force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Apartment__c/fields/Cost_of_Building__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Building__c</fullName>
    <label>Cost of Building</label>
    <precision>12</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Total_No_Of_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_No_Of_Units__c</fullName>
    <label>Total No Of Units</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Total_SqFt_of_the_Building__c.field-meta.xml
<CustomField>
    <fullName>Total_SqFt_of_the_Building__c</fullName>
    <label>Total SqFt of the Building</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Apartment_Name__c.field-meta.xml
<CustomField>
    <fullName>Apartment_Name__c</fullName>
    <label>Apartment Name</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>AppartmentUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Property__c/fields/Area_in_SqFt__c.field-meta.xml
<CustomField>
    <fullName>Area_in_SqFt__c</fullName>
    <label>Area in SqFt</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_ID__c.field-meta.xml
<CustomField>
    <fullName>Property_ID__c</fullName>
    <externalId>true</externalId>
    <label>Property ID</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Studio_Apartment</fullName>
                <label>Studio Apartment</label>
            </value>
            <value>
                <fullName>Loft</fullName>
            </value>
            <value>
                <fullName>Micro_Apartment</fullName>
                <label>Micro Apartment</label>
            </value>
            <value>
                <fullName>Pent_House</fullName>
                <label>Pent House</label>
            </value>
            <value>
                <fullName>Standard Apartment</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>2Bed 2Bath</fullName>
            </value>
            <value>
                <fullName>3Bed 2Bath</fullName>
            </value>
            <value>
                <fullName>3Bed 2.5Bath</fullName>
            </value>
            <value>
                <fullName>3Bed 3Bath</fullName>
            </value>
            <value>
                <fullName>4Bed 3Bath</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AptProp_Test.cls
@isTest
public class AptProp_Test {
    @isTest static void aptTest(){    
    
    	Apartment__c aptAdd = new Apartment__c(Name = 'Lake View Apartments', 
                       Total_SqFt_of_the_Building__c=30000, Cost_of_Building__c=6000000, Total_No_Of_Units__c=20);
        Test.startTest();
        Database.SaveResult aptSave = Database.insert(aptAdd,true);
        Test.stopTest();
        System.assert(aptSave.isSuccess());
        
}
        //Unit_Type__c='2Bed 2Bath',
        
        @isTest static void propTest(){
			Apartment__c aptAdd = new Apartment__c(Name = 'Lake View Apartments', 
                         Total_SqFt_of_the_Building__c=30000, Cost_of_Building__c=6000000, Total_No_Of_Units__c=20);
    		insert aptAdd;
       
        	Property__c propAdd = new Property__c(Apartment_Name__c=aptAdd.Id, Property_ID__c='DD212', 
                              Name='LakeView Flat', Area_in_SqFt__c=1000);
        	Test.startTest();
            Database.SaveResult propSave = Database.insert(propAdd,true);
        	Test.stopTest();
        	System.assert(propSave.isSuccess());
        
    }
    
/*
 * @isTest 
public class ControllerTestClass 
{
	 static testMethod void withPhoneNumber() 
	 {
		Account testAccount = new Account();
		testAccount.Name='Test Account' ;
		insert testAccount;

		Contact cont = new Contact ();
		cont.FirstName = 'FirstName';
		cont.LastName = 'LastName';
		cont.Email='email@email.com';
		cont.phone='12345678';
		insert cont;
		
		Test.StartTest(); 

			PageReference pageRef = Page.AccountPlan; // Add your VF page Name here
			pageRef.getParameters().put('phone', '234567');
			pageRef.getParameters().put('orderId', String.valueOf(testAccount.Id));
			Test.setCurrentPage(pageRef);

			ListContactDetailOnCallController testAccPlan = new ListContactDetailOnCallController();
			testAccPlan.redirPage();	
		Test.StopTest();
	 }
*/
}