force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Apartment__c/fields/Cost_of_Building__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Building__c</fullName>
    <label>Cost of Building</label>
    <precision>12</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Total_No_Of_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_No_Of_Units__c</fullName>
    <label>Total No Of Units</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Total_SqFt_of_the_Building__c.field-meta.xml
<CustomField>
    <fullName>Total_SqFt_of_the_Building__c</fullName>
    <label>Total SqFt of the Building</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Apartment_Name__c.field-meta.xml
<CustomField>
    <fullName>Apartment_Name__c</fullName>
    <label>Apartment Name</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>AppartmentUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/NewApartmentAndUnits.cls
public class NewApartmentAndUnits {
    public WrapAptProp wApt {get;set;}
   
    public String Idkey {get;set;}
    
    public NewApartmentAndUnits(){
        wApt = new WrapAptProp(new Apartment__c(), new List<Property__c>());
       // wApt.apt = new Apartment__c();
        Idkey = ApexPages.currentPage().getParameters().get('id');
        if(Idkey != null){
            wApt.apt = [select Id, Name, Total_SqFt_of_the_Building__c,Cost_of_Building__c, 
                       Cons_Cost_per_SqFt__c,Total_No_Of_Units__c from Apartment__c where id=:Idkey limit 1];
        }         
 		wApt.prop.add(new Property__c(Apartment_Name__c=wApt.apt.id));  
    }

    public void addrow(){
        	wApt.prop.add(new Property__c(Apartment_Name__c=wApt.apt.id));  
    }
    
    public PageReference newApartment(){
        insert wApt.apt;
        PageReference aptPage = new PageReference('/apex/ApartmentDetails?&id='+wApt.apt.Id);
        aptPage.setRedirect(true);
        return aptPage;
    }

    public PageReference newProperties(){
        return new PageReference('/apex/NewProperties');
    }
    
    public PageReference saveProperties(){     
        insert wApt.prop;
        return new PageReference('/apex/PropList'); 
    }     
   
    public class wrapAptProp {
	    public Apartment__c apt {get; set;}
    	public List<Property__c> prop {get; set;} 

        public wrapAptProp(Apartment__c aptList, List<Property__c> propList) {
            apt = aptList;
            prop = propList;
        }
    } 
}